### ISSUE TITLE
Can you provide your telegram username

### ISSUE THREAD

**Issue by Pranav-Talmale** [XanderFromFortnite/samsung_a3core_twrp#6]
I am a fellow dev. wanting to work on the device. So wanted to talk to you about your findings.....

**Comment by XanderFromFortnite** [comment]
O, that's nice

**Comment by XanderFromFortnite** [comment]
well, I don't have a telegram account, what I do have is a matrix space

https://matrix.to/#/#samsunga03*:matrix.org

**Comment by XanderFromFortnite** [comment]
@Pranav-Talmale ok so it does look like I do have a telegram account, idk when I made it but a telegram account is linked to my phone number

**Comment by XanderFromFortnite** [comment]
Telegram: https://t.me/twrpsamsunga03core

**Comment by Pranav-Talmale** [comment]
Do DM me, my I'd is @raphael_alpha

**Comment by XanderFromFortnite** [comment]
Okie so uh

**Comment by XanderFromFortnite** [comment]
I have been locked out of my telegram

**Comment by XanderFromFortnite** [comment]
I can't login via SMS

It's asking for code via another device, the problem is that I login to telegram when I was on windows, now that i'm using linux, idk wut to do

**Comment by be4zad** [comment]
It's good idea to create a Telegram and Matrix group and bridge it with bot. If you want, I can.

**Comment by XanderFromFortnite** [comment]
really?
go ahead

**Comment by be4zad** [comment]
Matrix: [#galaxya03coretwrp:matrix.org](https://matrix.to/#/#galaxya03coretwrp:matrix.org) and [#telegram_a03coretwrp:t2bot.io](https://matrix.to/#/#telegram_a03coretwrp:t2bot.io)

Telegram: https://t.me/a03coretwrp
